name: dart_apitool
description: A tool to analyze the public API of a package, create a model of it and diff it against another version to check semver.
homepage: https://devmil.de
repository: https://github.com/devmil/dart_apitool

version: 0.8.0-dev

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  analyzer: ^5.2.0
  args: ^2.3.1
  collection: ^1.16.0
  colorize: ^3.0.0
  colorize_lumberdash: ^3.0.0
  console: ^4.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  lumberdash: ^3.0.0
  path: ^1.8.2
  plist_parser: ^0.0.9
  pub_semver: ^2.1.1
  pubspec_parse: ^1.2.0
  stack: ^0.2.1
  tuple: ^2.0.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  freezed: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.4

executables:
  dart-apitool: main
